server:
  port: 8082

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.7:30005
        namespace: seata-space
        group: SEATA_GROUP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456


mybatis-plus:
  ### 扫描mapper的xml文件
  mapper-locations: classpath:/mappers/*.xml
  ###实体扫描，多个package用逗号或者分号分隔
  #枚举和数据库自动转化配置
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 192.168.20.7:30005
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: seata-space
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.20.7:30005
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: seata-space
